name: Docker Image CI

on:
  push:
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        if: ${{ github.ref_name == 'master' }}
        with:
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_password }}

      - name: ETS2 Convoy Server | Build and Push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref_name == 'master' }}
          platforms: linux/amd64
          tags: |
            lshallo/ets2-convoy-server:latest
            lshallo/ets2-convoy-server:${{ env.RELEASE_VERSION }}