name: Docker Image CI

on:
  push:
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_password }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        if: ${{ github.ref_type == 'tag' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-ets2:
    runs-on: ubuntu-latest
    needs: ['prepare']
    permissions:
      contents: read
      packages: write

    steps:
      - name: ETS2 Convoy Server | Build and Push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref_type == 'tag' }}
          platforms: linux/amd64
          tags: |
            lshallo/ets2-convoy-server:latest
            lshallo/ets2-convoy-server:${{ env.RELEASE_VERSION }}
            ghcr.io/lshallo/ets2-convoy-server:latest
            ghcr.io/lshallo/ets2-convoy-server:${{ env.RELEASE_VERSION }}

  build-ats:
    runs-on: ubuntu-latest
    needs: ['prepare']
    permissions:
      contents: read
      packages: write

    steps:
      - name: ATS Convoy Server | Build and Push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref_type == 'tag' }}
          build-args: |
            APP_ID=2239530
            SAVEGAME_LOCATION=/root/.local/share/American Truck Simulator/
            EXECUTABLE=/app/bin/linux_x64/amtrucks_server
            DEFAULT_PACKAGES=default_packages/ats
          platforms: linux/amd64
          tags: |
            lshallo/ats-convoy-server:latest
            lshallo/ats-convoy-server:${{ env.RELEASE_VERSION }}
            ghcr.io/lshallo/ats-convoy-server:latest
            ghcr.io/lshallo/ats-convoy-server:${{ env.RELEASE_VERSION }}